version: "3.8"

services:
  core:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: ../../
      dockerfile: environments/Dockerfile
    env_file: ../envs.env
    tty: true
    volumes:
        - ../../:/home/challenger/cvpr2023survey
    ports:
        - 8000:8000